wavstegp : stego_main.c stego/stego.c stego/lsb.c utils/wavtool.c compress/compress.c crypto/crypto.c
	gcc -g stego_main.c stego/stego.c stego/lsb.c utils/wavtool.c compress/compress.c crypto/crypto.c crypto/aes.c -std=c99 -lm -lz -o wavstego
